### PR TITLE
Switch to using fork of project repository instead of copying a template

### LINKED ISSUE #249: Change initial retrieval of course project to be a fork rather than template copy
In order to enable changes to the code review section made in #226 , the learner acquisition of the course project needs to be changed from a template copy to a fork. Further details for why this is necessary in [this comment](https://github.com/carpentries-incubator/python-intermediate-development/pull/226#issuecomment-1737140464).

### PR DESCRIPTION
**Pull request by bielsnohr**
This PR implements the antecedent changes in the lesson to enable changes in #226 to work properly for learners. It should only be merged **after** that PR because it is based on top of that source branch. Closes #249 .

### CODE REVIEW

**Comment by anenadic** [comment]
Updated inflammation template repo with branches to use when reviewing this PR (that also needs to be synched with the original inflammation template repo): https://github.com/thomaskileyukaea/python-intermediate-inflammation-training-nov23

**Comment by bielsnohr** [comment]
> Updated inflammation template repo with branches to use when reviewing this PR (that also needs to be synched with the original inflammation template repo): https://github.com/thomaskileyukaea/python-intermediate-inflammation

@anenadic we agreed in the maintainers sprint that it is probably actually best to create a complete new and distinct learner project repo to avoid problems with any forked versions of this course. @steve-crouch please correct me on that if I misinterpreted.

Once we create that new repository, we can update the links here to point to it.

**Comment by anenadic** [comment]
Merging this PR to a separate branch on the base repo with the intention of merging it to dev branch and then to gh-pages next.

**Review by anenadic — APPROVED** [review]
Merging this to a new branch on the base repo. The next is merging this to dev after a round of reviews and then to gh-pages.

**Pull request merged**
