### PR TITLE
Apply semantic line breaks

### LINKED ISSUE #199: Reformat Markdown files to a max 100 character line length for increased readability

### PR DESCRIPTION
**Pull request by tobyhodges**
When completed, this will fix #199

It is going to take me a while, but I am breaking up and reformatting lines in the source .md files in an attempt to follow the specification for semantic line breaks.

Because this will end up being a very large PR, I'm opening it now with only `index.md` and first episode edited so far. Can I get some feedback from the maintainers and confirmation that I am on the right track please, before I continue?

I can't promise that the whole lesson will be done quickly - I am going to be doing this in spare time - but I'll get there eventually!

- [x] 00-setting-the-scene.md
- [x] 10-section1-intro.md
- [x] 11-software-project.md
- [x] 12-virtual-environments.md
- [x] 13-ides.md
- [x] 14-collaboration-using-git.md
- [x] 15-coding-conventions.md
- [x] 16-verifying-code-style-linters.md
- [x] 20-section2-intro.md
- [x] 21-automatically-testing-software.md
- [x] 22-scaling-up-unit-testing.md
- [x] 23-continuous-integration-automated-testing.md
- [x] 24-diagnosing-issues-improving-robustness.md
- [x] 30-section3-intro.md
- [x] 31-software-requirements.md
- [x] 32-software-design.md
- [x] 33-programming-paradigms.md
- [x] 34-functional-programming.md
- [x] 35-object-oriented-programming.md
- [x] 36-architecture-revisited.md
- [x] 40-section4-intro.md
- [x] 41-code-review.md
- [x] 42-software-reuse.md
- [x] 43-software-release.md
- [x] 50-section5-intro.md
- [x] 51-managing-software.md
- [x] 52-assessing-software-suitability-improvement.md
- [x] 53-improvement-through-feedback.md
- [x] 60-wrap-up.md
- [x] about.md
- [x] common-issues.md
- [x] databases.md
- [x] figures.md
- [x] guide.md
- [x] persistence.md
- [x] quiz.md
- [x] vscode.md

### CODE REVIEW

**Comment by tobyhodges** [comment]
Thanks for the feedback, @bielsnohr - I was indeed aiming for 100 characters max, based on the title of #199, but of course a few lines will go over where a break is either impossible or I judge it would make the file less readable.

**Comment by tobyhodges** [comment]
@carpentries-incubator/python-intermediate-rsd-maintainers I have worked through all of the episodes now and hope to get through the files in `_extras` tomorrow, after which this PR will only be blocked by #205 

If you can reply to that issue with updated wording, I am happy to add that into my changes for the episode in this PR. If you would prefer that I leave the text of that episode as-is in this branch, I will apply line breaks only. Please let me know how you would like me to proceed.

**Comment by tobyhodges** [comment]
Thanks @steve-crouch for resolving #205 I have now pushed the sembr-ed version of episode 42 (incorporating Steve's suggested wording) and this is finally ready for review and merge.

**Review by bielsnohr — CHANGES_REQUESTED** [review]
Thanks again @tobyhodges for this extensive amount of work on re-formatting the course files. I started reviewing the actual source files, but quickly realised that would be far too arduous for the entire course. Therefore, I switched to just making sure that the rendering of the website looked roughly correct. I have done that for all pages and am satisfied the coures website renders as it did before these changes, which is exactly what we want.

I have requested changes on the one file that I looked at in depth. I imagine that there would be similar changes for the other files, but I am adopting the approach that we can make those adjustments incrementally at the time we are making other modifications to the material.

I want this PR to get through as quick as possible because it is invariably blocking other concurrent work from happening. I myself have held off making some changes because I knew that they would cause merge conflicts with whatever was done here.

@anenadic and @steve-crouch could you give a quick yay/nay whether you are satisfied with me being the only maintainer to okay these changes and then merge?

**Review by bielsnohr — APPROVED** [review]

**Comment by bielsnohr** [comment]
After verbal confirmation from @anenadic in a maintainer meeting, I am going to proceed and merge this. Thanks again @tobyhodges for the great work on this.

**Comment by anenadic** [comment]
You beat me to it @bielsnohr. Many thanks to @tobyhodges for this.

**Pull request merged**
