### PR TITLE
Update 24-diagnosing-issues-improving-robustness.md

### PR DESCRIPTION
**Pull request by jreeve-nv**
Corrected error where the automating pylint section creates a branch named `pylint-ci` but then merges `test-suite` back into `develop`. Now the merge back into `develop` is with the `pylint-ci` branch.

### CODE REVIEW

**Comment by bielsnohr** [comment]
Likely related to #365

**Comment by steve-crouch** [comment]
Also related to #383, which appears to have a different solution to the same issue if I understand it correctly. After discussing it with Aleks, we'll need to work out the best way forward after the material has transitioned to the new format which has become a priority. We'll recreate the PR after that. At least we're not short on solutions for this :)

**Comment by bielsnohr** [comment]
Thanks for the contribution @jreeve-nv and comments @steve-crouch 

As I detailed in [this comment](https://github.com/carpentries-incubator/python-intermediate-development/issues/365#issuecomment-2427309386), this is actually solved if we just get rid of creation and mention of the `pylint-ci` branch and continue working on the `test-suite` branch that learners _should_ already be on at this point in the lesson. I have done a search through the lesson material, and there is no other reference to `pylint-ci` anywhere else in the lesson, so this should be a safe change with no knock-on effects.

@jreeve-nv I have pushed updates to your PR to reflect these comments. Will wait for another member of the maintainer team to approve before we go ahead and merge.

**Review by steve-crouch — APPROVED** [review]
Just tested this suggested change to the branch instructions and it all works as expected.

**Review by anenadic — APPROVED** [review]

**Pull request merged**
